### ISSUE TITLE
Issue with pip installing Chessnut module

### ISSUE THREAD

**Issue by l4nk332** [cgearhart/Chessnut#11]
There was an issue my team and I had when writing an AI that works alongside Chessnut. For some reason, even after following the installation instructions and pip installing into a virtual environment, we were unable to capture a piece that was putting our king in check. We had checked the list of moves (from Game.get_moves()) and the move was not found.

Here is the fen of the board state:

rnb1kbnr/pppp1ppp/4p3/8/2B1P3/5N2/PPPP1P1P/RNBQK1q1 w Qkq - 0 5

**Comment by cgearhart** [comment]
Thanks for the bug report. I won't be able to dig into this until the weekend, but I'll get it resolved ASAP and push an update.

**Comment by cgearhart** [comment]
Looks like this was fixed after the release of 0.3.0, but I never pushed an update to the package. You should be able to run `pip install --upgrade Chessnut` to resolve the error.
