### ISSUE TITLE
Status Codes - Who wins?

### ISSUE THREAD

**Issue by jacobmenick** [cgearhart/Chessnut#7]
Nice to have - if there were some state variable for who is in checkmate.

**Comment by cgearhart** [comment]
You should be able to use the game status, which is from the perspective of the active player. So if you reach `status == Game.CHECKMATE`, you can find the *loser* with `loser = game_instance.state.player`

I'm not sure what you're use case is, but be aware that Chessnut doesn't validate boards when a Game instance is instantiation; the behavior is undefined if you're trying to feed in an invalid board -- e.g., if both players are in checkmate. You could work around it by testing the same state for both players if it matters to you, but it's not something I plan to support in the library.

**Comment by jacobmenick** [comment]
Okay - I see why getting the info I need doesn't require any change in the code. Thanks
