### ISSUE TITLE
Valid move missing for self.get_moves()

### ISSUE THREAD

**Issue by BastiTee** [cgearhart/Chessnut#9]
Hey, I've found a fen string for that you'll not receive the correct list of valid moves. The minimal test:
```
from Chessnut.game import Game
chessgame = Game()
chessgame.set_fen('r3kb1r/p1p2pp1/2p4p/3Pp3/6b1/2P5/PP1NN2P/R2QK1q1 w Qkq - 0 16')
try:
    assert (chessgame.get_moves() == ['d2f1', 'e2g1'])
    print 'Test passed.'
except AssertionError:
    print 'Test failed.'
```

The FEN corresponds to this position with white to move. Chessnut only returns the d2f1 move, but fails to return e2g1 knight capturing the queen. 
![fen](https://cloud.githubusercontent.com/assets/7995100/13639309/7f30621a-e610-11e5-833c-679675ea30ef.png)

**Comment by BastiTee** [comment]
Okay, I've found the problem. It happens during the evaluation if a possible move is a castle out of the check. At this point it is not verified if the move involves the king at all. e2g1 is therefore evaluated as if the king moved e1g1. Fixed on my pull request.

**Comment by cgearhart** [comment]
Nice work. Let me verify tonight & I'll merge the fix.

**Comment by cgearhart** [comment]
I merged the pull request with the fix & then noticed that the test could be simplified & more efficiently conducted by splitting the conditional. Those changes were included in the push to fix issue 10.

It currently passes all of the unit tests (including a new one for this issue), but I'll wait to see if you have any comments before I uprev the library release in the pypi package.

Thanks again.

**Comment by BastiTee** [comment]
I ran the new code on my data and I got nothing. Thanks!
